### ISSUE TITLE
The sounds can be heard serverwide

### ISSUE THREAD

**Issue by fireglow** [D00Med/vehicles#15]
We tested the mod on our server and a problem caused us to remove it again:
The sounds can be heard by every player on the server.

**Comment by D00Med** [comment]
That is a big problem, but I don't know how I can fix it, maybe just by limiting it to the driver.
I could make them play at the position of the vehicle, but I don't think that will work too well, considering that the sounds have a long duration

**Comment by D00Med** [comment]
I think it is fixed now
