### ISSUE TITLE
Replace default boat

### ISSUE THREAD

**Issue by tacotexmex** [D00Med/vehicles#23]
I'd like to find a way to replace all minetest_game boats with vechicles mod boats. Already placed ones and recipe wise. Is there a way of doing this?

**Comment by D00Med** [comment]
Is this the speed boat you are talking about?
I think you could probably override the boat item, so that it's like a vehicles mod spawner.

**Comment by tacotexmex** [comment]
I may have assumed that the default _looking_ vehicles mod boat in Farlands was also represented in the vehicle collection of the regular mod, without looking into it, sorry.

Regardless, how would I override the default boat? I can see myself cancelling out the loading of the boat mod and load the vehicle mod instead, but how would i replace placed, in-world boats?

**Comment by D00Med** [comment]
No not yet, I will add it later.
Well I don't actually know, like I said you could just override the spawner so that the item is the same, but places a different boat entity. That would mean the crafting recipes are the same.

**Comment by tacotexmex** [comment]
Alright, I think I'll override the recipe and just let the old boat become an unknown node. Thank you.
