### ISSUE TITLE
Cannot find launcher/player of missile crashes server

### ISSUE THREAD

**Issue by MegaMark16** [D00Med/vehicles#25]
Under certain circumstances the launcher of a missile cannot be found (maybe if a player launches a missile and then disconnects, I'm not exactly sure) and it starts crashing as soon as someone connects to the server with:

` vehicles/init.lua:44:` attempt to index local 'player' (a nil value)

I have a fix, not sure if it's a good one, but I wanted to log an issue first so there's a place to document discussions around this issue and my possible fix.

**Comment by D00Med** [comment]
Thankyou for this. Your change for the standing animation won't work though, "entity.moving_anim" doesn't exist. I will merge your changes(and fix the animation name) when I next update the mod.
