### ISSUE TITLE
Vehicle spawner items are mining tools

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/vehicles#7]
It appears that all vehicle spawners (e.g. `vehicles:ambulance_spawners`) can be used as mining tools and even as weapon.

For some reason, an ambulance spawner is able to dig snappy nodes faster than the hand.

This doesn't seem right. Can you please check your item definitions?

I noticed this while developing my `doc_items` mod which shows digging times for all tools in latest development version.

**Comment by D00Med** [comment]
Thankyou for pointing this out. 
I have changed the spawners to craftitems instead of tools
